import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#c3c0ff",
        "on-background": "#1a1c1b",
        "primary": "#3525cd",
        "secondary-fixed": "#e4e2e2",
        "inverse-primary": "#c3c0ff",
        "surface-container": "#efeeec",
        "inverse-surface": "#2f3130",
        "surface-dim": "#dadad8",
        "surface": "#faf9f7",
        "on-error-container": "#93000a",
        "tertiary-container": "#a44100",
        "tertiary": "#7e3000",
        "on-primary-fixed": "#0f0069",
        "outline": "#777587",
        "on-secondary-container": "#626262",
        "surface-container-highest": "#e3e2e0",
        "secondary-fixed-dim": "#c7c6c6",
        "secondary-container": "#e1dfdf",
        "primary-fixed": "#e2dfff",
        "surface-bright": "#faf9f7",
        "on-tertiary-fixed-variant": "#7b2f00",
        "surface-variant": "#e3e2e0",
        "on-tertiary-container": "#ffd2be",
        "background": "#faf9f7",
        "surface-tint": "#4d44e3",
        "surface-container-high": "#e9e8e6",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-low": "#f4f3f1",
        "on-surface-variant": "#464555",
        "on-primary-fixed-variant": "#3323cc",
        "error": "#ba1a1a",
        "secondary": "#5e5e5e",
        "on-secondary-fixed": "#1b1c1c",
        "inverse-on-surface": "#f1f1ef",
        "on-primary-container": "#dad7ff",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffdbcc",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#464747",
        "primary-container": "#4f46e5",
        "on-primary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-surface": "#1a1c1b",
        "on-tertiary-fixed": "#351000",
        "error-container": "#ffdad6"
      },
      fontFamily: {
        "headline": ["var(--font-fraunces)", "serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-inter)", "sans-serif"],
        "serif": ["var(--font-fraunces)", "serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [],
};
export default config;
